### ISSUE TITLE
support null safety

### ISSUE THREAD

**Issue by callmejm** [UnluckyY1/Flutter_easy_cart_animation#1]
please support null safety

**Comment by UnluckyY1** [comment]
> please support null safety

i will update it this week

**Comment by saigkl** [comment]
Any Updates @UnluckyY1?

**Comment by UnluckyY1** [comment]
Done already 

You  can simply link to it via syntax like that until i update it on pub.dev :

```
 easycartanimation:
    git:
      url: https://github.com/UnluckyY1/Flutter_easy_cart_animation.git
```
